language: ruby
rvm:
  - 2.5.0

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec

services:
  - postgresql

notifications:
  email: false
